DROP TABLE IF EXISTS MEASUREMENT;
DROP TABLE IF EXISTS PATIENT;
DROP TABLE IF EXISTS DOCTOR;
DROP TABLE IF EXISTS PERSON;

-- CREATE TABLES

CREATE TABLE PERSON (
	ID INT PRIMARY KEY AUTO_INCREMENT,
    FISCAL_CODE VARCHAR(20) NOT NULL,
    NAME VARCHAR(50),
    SURNAME VARCHAR(50),
    DATE_OF_BIRTH DATE,
    SEX ENUM('M', 'F'), 
    EMAIL VARCHAR(255), 
    PHONE_NUMBER VARCHAR(15),
    IMAGE_PATH VARCHAR(512)
    );
    
CREATE TABLE DOCTOR (
	ID INT PRIMARY KEY AUTO_INCREMENT,
	SPECIALIZATION VARCHAR(50) NOT NULL,
    PASSWORD VARCHAR(255) NOT NULL,
	PERSON_ID INT UNIQUE NOT NULL,
	FOREIGN KEY (PERSON_ID) REFERENCES PERSON (ID)
);

CREATE TABLE PATIENT(
	ID INT PRIMARY KEY AUTO_INCREMENT,
	MEDICAL_CONDITION VARCHAR(255) NOT NULL,
    WEIGHT INT,
    COUNTRY VARCHAR(2),
	PERSON_ID INT NOT NULL,
	DOCTOR_ID INT NOT NULL,
	FOREIGN KEY (PERSON_ID) REFERENCES PERSON (ID),
	FOREIGN KEY (DOCTOR_ID) REFERENCES DOCTOR (ID)
);

CREATE TABLE MEASUREMENT(
	ID INT PRIMARY KEY AUTO_INCREMENT,
    M_TIMESTAMP TIMESTAMP,
    M_TYPE ENUM('BRAINWAVES','SATURATION','HEART_FREQUENCY'),
    CSV_PATH VARCHAR(512),
    PATIENT_ID INT NOT NULL,
    FOREIGN KEY (PATIENT_ID) REFERENCES PATIENT (ID)
);

    
-- CREATE TRIGGERS

DELIMITER $$

CREATE TRIGGER CHECK_SINGLE_AT
BEFORE INSERT ON PERSON
FOR EACH ROW
	BEGIN
		IF (LENGTH(NEW.email) - LENGTH(REPLACE(NEW.email, '@', '')) <> 1) THEN	-- IF IT DOESN'T CONTAIN ONE @
			SIGNAL SQLSTATE '45000'
			SET MESSAGE_TEXT = 'Email must contain exactly one "@" symbol';
		END IF;
	END $$

DELIMITER ;
		
    